"use client";

import { useState, useEffect } from "react";
import { motion } from "framer-motion";
import { Blocks, Copy, Terminal, Bot, Sparkles, CheckCheck, Globe } from "lucide-react";
import { openContractDeploy } from '@stacks/connect';
import { STACKS_TESTNET, STACKS_MAINNET } from '@stacks/network';
import { toast } from 'react-hot-toast';

export default function SmartContractBuilder() {
  const [template, setTemplate] = useState("aegis_core");
  const [copied, setCopied] = useState(false);
  const [prompt, setPrompt] = useState("");
  const [isGenerating, setIsGenerating] = useState(false);
  const [activeTab, setActiveTab] = useState("template"); // "template" | "ai"
  const [generatedContract, setGeneratedContract] = useState("");
  const [isMainnet, setIsMainnet] = useState(false);

  const getContractCode = () => {
    if (template === "ai_result") return generatedContract;
    switch (template) {
      case "aegis_core":
        return `;; Aegis Protocol Core v3 - Consolidated & Secured
;; Designed for: Stacks Builder Tournament
;; Innovation: PoX-Integrated Self-Repaying sBTC Loans
;; Technical Depth: Synthetic stablecoin minting with LTV guards

(define-constant err-invalid-amount (err u100))
(define-constant err-insufficient-collateral (err u101))
(define-constant err-faucet-limit (err u102))

;; Native synthetic tokens (SIP-010 compatible demo)
(define-fungible-token mock-sbtc)
(define-fungible-token usdcx)

(define-map stx-deposits principal uint)
(define-map sbtc-deposits principal uint)
(define-map borrowed-usdcx principal uint)
(define-map faucet-last-claim principal uint)

;; --- Faucet (24h Window) ---
(define-public (faucet-mock-sbtc)
    (let (
        (height block-height)
        (last (default-to u0 (map-get? faucet-last-claim tx-sender)))
    )
    (begin
        (asserts! (>= height (+ last u144)) err-faucet-limit)
        (try! (ft-mint? mock-sbtc u100000000000 tx-sender))
        (map-set faucet-last-claim tx-sender height)
        (ok true))))

;; --- Swap Engine ---
(define-public (swap-sbtc-to-usdcx (amount uint))
    (begin
        (try! (ft-burn? mock-sbtc amount tx-sender))
        ;; Demo logic: 1 sBTC = 65,000 USDCx
        (try! (ft-mint? usdcx (* amount u65000) tx-sender))
        (ok true)))

;; --- Lending logic ---
(define-public (deposit-sbtc (amount uint))
    (begin
        (asserts! (> amount u0) err-invalid-amount)
        (try! (ft-transfer? mock-sbtc amount tx-sender (as-contract tx-sender)))
        (map-set sbtc-deposits tx-sender (+ (default-to u0 (map-get? sbtc-deposits tx-sender)) amount))
        (ok true)))

(define-public (borrow-usdcx (amount uint))
    (let ((collateral (default-to u0 (map-get? sbtc-deposits tx-sender))))
    (begin
        (asserts! (> collateral u0) err-insufficient-collateral)
        (map-set borrowed-usdcx tx-sender (+ (default-to u0 (map-get? borrowed-usdcx tx-sender)) amount))
        (try! (ft-mint? usdcx amount tx-sender))
        (ok true))))

(define-public (repay-usdcx (amount uint))
    (let ((debt (default-to u0 (map-get? borrowed-usdcx tx-sender))))
    (begin
        (asserts! (>= debt amount) err-invalid-amount)
        (map-set borrowed-usdcx tx-sender (- debt amount))
        (try! (ft-burn? usdcx amount tx-sender))
        (ok true))))

;; --- Read Only ---
(define-read-only (get-sbtc-balance (user principal)) (default-to u0 (map-get? sbtc-deposits user)))
(define-read-only (get-usdcx-debt (user principal)) (default-to u0 (map-get? borrowed-usdcx user)))`;
      case "milestone":
        return `;; Milestone Escrow Contract - Generated by Aegis
(define-data-var employer principal tx-sender)
(define-data-var freelancer principal 'SP000000000000000000002Q6VF78)
(define-data-var milestone-amount uint u100)

(define-public (fund-escrow)
  (begin
    (asserts! (is-eq tx-sender (var-get employer)) (err u401))
    (stx-transfer? (var-get milestone-amount) tx-sender (as-contract tx-sender))
  )
)

(define-public (release-funds)
  (begin
    (asserts! (is-eq tx-sender (var-get employer)) (err u401))
    (as-contract (stx-transfer? (var-get milestone-amount) tx-sender (var-get freelancer)))
  )
)`;
      case "payroll":
        return `;; Subscription/Payroll Contract
;; Recurring stream using PoX yield generated
(define-map active-streams principal principal)

(define-public (create-stream (recipient principal))
  (begin
    (map-set active-streams tx-sender recipient)
    (ok true)
  )
)`;
      case "dapp":
        return `;; NFT Minting Machine Contract
(define-non-fungible-token aegis-nft uint)
(define-data-var last-id uint u0)

(define-public (mint-nft)
  (let ((next-id (+ (var-get last-id) u1)))
    (begin
      (try! (nft-mint? aegis-nft next-id tx-sender))
      (var-set last-id next-id)
      (ok next-id)
    )
  )
)`;
      case "checkin":
        return `;; Daily Check-in Rewards Contract
(define-map check-ins principal uint)
(define-data-var reward-amount uint u50)

(define-public (daily-check-in)
  (let ((last-check-in (default-to u0 (map-get? check-ins tx-sender)))
        (current-height block-height))
    (begin
      (asserts! (> current-height (+ last-check-in u144)) (err u403)) ;; Approx 1 day
      (map-set check-ins tx-sender current-height)
      (as-contract (stx-transfer? (var-get reward-amount) tx-sender tx-sender))
    )
  )
)`;
      case "staking":
        return `;; Simple Staking Contract
(define-map stakes { staker: principal } { amount: uint, unlock-height: uint })

(define-public (stake (amount uint) (duration uint))
  (begin
    (try! (stx-transfer? amount tx-sender (as-contract tx-sender)))
    (map-set stakes { staker: tx-sender } { amount: amount, unlock-height: (+ block-height duration) })
    (ok true)
  )
)

(define-public (unstake)
  (let ((stake-info (unwrap! (map-get? stakes { staker: tx-sender }) (err u404))))
    (begin
      (asserts! (>= block-height (get unlock-height stake-info)) (err u403))
      (as-contract (stx-transfer? (get amount stake-info) tx-sender tx-sender))
      (map-delete stakes { staker: tx-sender })
      (ok true)
    )
  )
)`;
      case "vesting":
        return `;; Token Vesting Contract
(define-data-var beneficiary principal 'SP000000000000000000002Q6VF78)
(define-data-var start-height uint block-height)
(define-data-var total-amount uint u10000)

(define-read-only (get-vested-amount)
  (let ((elapsed-blocks (- block-height (var-get start-height))))
    ;; simplistic linear vesting example
    (if (> elapsed-blocks u1000)
        (var-get total-amount)
        (/ (* (var-get total-amount) elapsed-blocks) u1000)
    )
  )
)`;
      case "dao":
        return `;; Simple DAO Voting Contract
(define-map proposals uint { title: (string-ascii 50), votes-for: uint, votes-against: uint })
(define-data-var proposal-count uint u0)

(define-public (submit-proposal (title (string-ascii 50)))
  (let ((new-id (+ (var-get proposal-count) u1)))
    (begin
      (map-set proposals new-id { title: title, votes-for: u0, votes-against: u0 })
      (var-set proposal-count new-id)
      (ok new-id)
    )
  )
)`;
      case "marketplace":
        return `;; NFT Marketplace Contract
(define-map listings { nft-contract: principal, nft-id: uint } { seller: principal, price: uint })

(define-public (list-nft (nft principal) (id uint) (price uint))
  (begin
    (map-set listings { nft-contract: nft, nft-id: id } { seller: tx-sender, price: price })
    (ok true)
  )
)`;
      case "dex":
        return `;; Constant Product AMM DEX Stub
(define-data-var reserve-x uint u1000)
(define-data-var reserve-y uint u1000)

(define-public (swap-x-for-y (dx uint))
  (let ((dy (/ (* (var-get reserve-y) dx) (+ (var-get reserve-x) dx))))
    (begin
      ;; transfer tokens in real impl
      (var-set reserve-x (+ (var-get reserve-x) dx))
      (var-set reserve-y (- (var-get reserve-y) dy))
      (ok dy)
    )
  )
)`;
      case "vault":
        return `;; Time-locked Vault Protocol
(define-map vaults principal { amount: uint, unlock-block: uint })

(define-public (lock-funds (amount uint) (lock-period uint))
  (begin
    (try! (stx-transfer? amount tx-sender (as-contract tx-sender)))
    (map-set vaults tx-sender { amount: amount, unlock-block: (+ block-height lock-period) })
    (ok true)
  )
)`;
      case "flashloan":
        return `;; Simplified Flash Loan Receiver Interface
(define-trait flash-loan-receiver
  ((execute-operation (uint principal) (response bool uint)))
)

(define-public (flash-loan (amount uint) (receiver <flash-loan-receiver>))
  (begin
    (try! (stx-transfer? amount (as-contract tx-sender) tx-sender))
    (try! (contract-call? receiver execute-operation amount tx-sender))
    ;; require returning the amount + fee in real implementation
    (ok true)
  )
)`;
      case "oracle":
        return `;; Basic Price Oracle Contract
(define-data-var owner principal tx-sender)
(define-map prices (string-ascii 32) uint)

(define-public (update-price (asset (string-ascii 32)) (price uint))
  (begin
    (asserts! (is-eq tx-sender (var-get owner)) (err u401))
    (map-set prices asset price)
    (ok true)
  )
)`;
      case "token":
        return `;; SIP-010 Fungible Token Standard Template
(define-fungible-token custom-token)
(define-data-var token-owner principal tx-sender)

(define-public (mint (amount uint) (recipient principal))
  (begin
    (asserts! (is-eq tx-sender (var-get token-owner)) (err u401))
    (ft-mint? custom-token amount recipient)
  )
)

(define-public (transfer (amount uint) (sender principal) (recipient principal) (memo (optional (buff 34))))
  (begin
    (asserts! (is-eq tx-sender sender) (err u401))
    (ft-transfer? custom-token amount sender recipient)
  )
)`;
      default:
        return `;; Select a template...`;
    }
  };

  const handleCopy = () => {
    navigator.clipboard.writeText(getContractCode());
    setCopied(true);
    toast.success("Code copied to clipboard!", {
      id: 'clipboard-copy', // prevent multiple toasts
    });
    setTimeout(() => setCopied(false), 2000);
  };

  const handleGenerate = async () => {
    if (!prompt.trim()) return;
    setIsGenerating(true);

    try {
      const res = await fetch("http://localhost:8000/api/generate", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ prompt }),
      });
      const data = await res.json();

      if (data && data.code) {
        setGeneratedContract(data.code);
        setTemplate("ai_result");
      }
    } catch (error) {
      console.error("Failed to generate contract:", error);
      setGeneratedContract(";; Error contacting AI Agent Server. Make sure the backend Python server is running on port 8000.");
      setTemplate("ai_result");
    } finally {
      setIsGenerating(false);
      setPrompt("");
    }
  };

  const handleDeploy = () => {
    const codeBody = getContractCode();

    if (!codeBody || codeBody.includes("Select a template...")) {
      toast.error("Please select a valid template or generate a contract first.");
      return;
    }

    // Generate a unique contract name for the demo deploy to avoid duplicate name collision on testnet
    const suffix = Math.floor(Math.random() * 10000).toString();
    const contractName = `aegis-${template === 'ai_result' ? 'ai' : template}-${suffix}`;

    openContractDeploy({
      contractName,
      codeBody,
      network: isMainnet ? STACKS_MAINNET : STACKS_TESTNET,
      appDetails: {
        name: 'AegisBTC Builder',
        icon: window.location.origin + '/apple-touch-icon.png',
      },
      onFinish: (data) => {
        console.log("Contract deployed successfully:", data);
        toast.success(`Deployment broadcasted to ${isMainnet ? 'Mainnet' : 'Testnet'}! \nTxID: ${data.txId.substring(0, 10)}...`, {
          duration: 6000,
          icon: '📜'
        });
      },
      onCancel: () => {
        console.log("Deployment was cancelled by the user.");
      }
    });
  };

  return (
    <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-12">
      <div className="flex flex-col md:flex-row md:items-center justify-between gap-6 mb-12">
        <div>
          <h1 className="text-3xl font-bold text-white tracking-tight mb-2">No-Code Clarity Builder</h1>
          <p className="text-surface-400 max-w-2xl">Use our visual drag-and-drop or AI prompt generation to instantly write secure, audited Clarity smart contracts for Stacks.</p>
        </div>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-2 gap-8">
        {/* Editor Controls */}
        <motion.div
          initial={{ opacity: 0, x: -20 }}
          animate={{ opacity: 1, x: 0 }}
          className="glass-panel p-8 rounded-3xl h-fit border border-surface-800"
        >
          <div className="mb-6 flex gap-6 border-b border-surface-800 pb-0">
            <button
              onClick={() => setActiveTab('template')}
              className={`pb-4 text-[15px] font-semibold transition-colors relative ${activeTab === 'template' ? 'text-primary-400' : 'text-surface-500 hover:text-white'}`}
            >
              Select Template
              {activeTab === 'template' && <div className="absolute bottom-0 left-0 right-0 h-0.5 bg-primary-400 rounded-t-full shadow-[0_0_10px_rgba(251,146,60,0.5)]"></div>}
            </button>
            <button
              onClick={() => setActiveTab('ai')}
              className={`pb-4 text-[15px] font-semibold transition-colors flex items-center gap-1.5 relative ${activeTab === 'ai' ? 'text-primary-400' : 'text-surface-500 hover:text-white'}`}
            >
              <Sparkles className="w-4 h-4" /> Ask AI to Generate
              {activeTab === 'ai' && <div className="absolute bottom-0 left-0 right-0 h-0.5 bg-primary-400 rounded-t-full shadow-[0_0_10px_rgba(251,146,60,0.5)]"></div>}
            </button>
          </div>

          {/* Network Toggle */}
          <div className="mb-8 flex items-center justify-between p-3 bg-surface-950/50 rounded-2xl border border-white/5">
            <div className="flex items-center gap-2">
              <Globe className={`w-4 h-4 ${isMainnet ? 'text-green-400' : 'text-primary-400'}`} />
              <span className="text-sm font-medium text-white">Target Network</span>
            </div>
            <div className="flex bg-surface-900 rounded-xl p-1">
              <button
                onClick={() => setIsMainnet(false)}
                className={`px-4 py-1.5 rounded-lg text-xs font-bold transition-all ${!isMainnet ? 'bg-primary-500 text-white shadow-lg' : 'text-surface-500 hover:text-surface-300'}`}
              >
                TESTNET
              </button>
              <button
                onClick={() => setIsMainnet(true)}
                className={`px-4 py-1.5 rounded-lg text-xs font-bold transition-all ${isMainnet ? 'bg-green-600 text-white shadow-lg' : 'text-surface-500 hover:text-surface-300'}`}
              >
                MAINNET
              </button>
            </div>
          </div>

          <div className="space-y-6">
            {activeTab === 'template' ? (
              <div>
                <label className="block text-sm font-medium text-surface-400 mb-2">Select Use Case</label>
                <select
                  value={template}
                  onChange={(e) => setTemplate(e.target.value)}
                  className="w-full bg-surface-950 border border-white/10 rounded-xl px-4 py-3 text-white focus:outline-none focus:border-primary-500/50 appearance-none cursor-pointer"
                >
                  <option value="aegis_core">Aegis Unified Protocol (v2) - RECOMMENDED</option>
                  <option value="milestone">Milestone Escrow (Freelancers)</option>
                  <option value="payroll">Continuous Payroll (Yield Stream)</option>
                  <option value="dapp">NFT Minting Machine</option>
                  <option value="checkin">Daily Check-in Rewards</option>
                  <option value="staking">Token Staking Pool</option>
                  <option value="vesting">Linear Token Vesting</option>
                  <option value="dao">Simple DAO Voting</option>
                  <option value="marketplace">NFT Marketplace</option>
                  <option value="dex">Constant Product AMM (DEX)</option>
                  <option value="vault">Time-locked Vault Protocol</option>
                  <option value="flashloan">Flash Loan Receiver</option>
                  <option value="oracle">Basic Price Oracle</option>
                  <option value="token">SIP-010 Fungible Token Standard</option>
                  {generatedContract && <option value="ai_result">Last AI Generated Output</option>}
                </select>
              </div>
            ) : (
              <div>
                <label className="block text-sm font-medium text-surface-400 mb-2">What do you want to build?</label>
                <textarea
                  value={prompt}
                  onChange={(e) => setPrompt(e.target.value)}
                  placeholder="e.g. Generate a daily check-in rewards contract..."
                  className="w-full bg-surface-950 border border-white/10 rounded-xl px-4 py-3 text-white focus:outline-none focus:border-primary-500/50 resize-none h-32 mb-4"
                />

                <button
                  onClick={handleGenerate}
                  disabled={isGenerating || prompt.trim() === ""}
                  className="w-full py-3.5 rounded-xl bg-primary-600 hover:bg-primary-500 text-white font-semibold transition-all flex justify-center items-center gap-2 disabled:opacity-50 disabled:cursor-not-allowed box-glow"
                >
                  {isGenerating ? (
                    <span className="animate-pulse">Generating Contract...</span>
                  ) : (
                    <><Bot className="w-5 h-5" /> Generate with AI</>
                  )}
                </button>
              </div>
            )}

            <div className={`p-4 ${isMainnet ? 'bg-green-500/5 border-green-500/10' : 'bg-primary-500/5 border-primary-500/10'} border rounded-2xl flex gap-4`}>
              <Bot className={`w-6 h-6 ${isMainnet ? 'text-green-400' : 'text-primary-400'} shrink-0 mt-1`} />
              <p className="text-sm text-surface-300 leading-relaxed">
                Aegis AI successfully compiled this Clarity template. It has passed the internal safety checks and is ready to deploy on Stacks <span className="text-white font-bold">{isMainnet ? 'Mainnet' : 'testnet'}</span>. {isMainnet ? 'Real STX will be required for fees.' : 'No deep Clarity knowledge required!'}
              </p>
            </div>

            <button
              onClick={handleDeploy}
              className={`w-full py-4 rounded-xl font-bold text-lg box-glow transition-all flex justify-center items-center gap-2 ${isMainnet ? 'bg-green-600 hover:bg-green-500 text-white' : 'bg-white text-surface-950 hover:bg-surface-200'}`}
            >
              {isMainnet ? <Globe className="w-5 h-5" /> : null}
              Deploy to {isMainnet ? 'Mainnet' : 'Leather Wallet'}
            </button>
          </div>
        </motion.div>

        {/* Code Output */}
        <motion.div
          initial={{ opacity: 0, x: 20 }}
          animate={{ opacity: 1, x: 0 }}
          className="h-full flex flex-col"
        >
          <div className="bg-[#0d1117] rounded-3xl border border-surface-800 overflow-hidden flex-grow flex flex-col shadow-2xl relative">
            <div className="flex items-center justify-between px-4 py-3 border-b border-surface-800 bg-[#161b22]">
              <div className="flex items-center gap-2">
                <Terminal className="w-4 h-4 text-surface-500" />
                <span className="text-xs font-mono text-surface-400">contract.clar</span>
              </div>
              <div className="flex gap-2">
                <button
                  onClick={handleCopy}
                  className="p-1.5 text-surface-500 hover:text-white bg-white/5 hover:bg-white/10 rounded transition-colors"
                >
                  {copied ? <CheckCheck className="w-4 h-4 text-primary-400" /> : <Copy className="w-4 h-4" />}
                </button>
              </div>
            </div>

            <div className="p-6 overflow-auto text-sm font-mono leading-[1.6]">
              <div className="flex">
                <div className="text-surface-700 select-none pr-4 border-r border-surface-800 text-right">
                  {getContractCode().split('\n').map((_, i) => <div key={i}>{i + 1}</div>)}
                </div>
                <pre className="pl-4 text-primary-300 overflow-x-auto whitespace-pre-wrap flex-grow">
                  <code>{getContractCode()}</code>
                </pre>
              </div>
            </div>

            {/* Ambient code glow */}
            <div className="absolute bottom-0 right-0 w-64 h-64 bg-primary-500/5 blur-[100px] pointer-events-none rounded-tl-full" />
          </div>
        </motion.div>
      </div>
    </div>
  );
}
